[build-system]
requires = [
    "pytest",
    "setuptools>=42",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = [
    "pytest>=7.2.2",
]
test-command = "pytest"
test-skip = "*universal2:arm64"
